# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3QAXvrzuNKEsN9EAmnn4nAe-V9uvQeB
"""

# src/train.py
import os
import pandas as pd
import joblib
import mlflow
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report


def train_model(
    data_path: str,
    target_col: str,
    model_out: str,
    vectorizer_out: str,
    log_path: str,
    max_features: int = 5000,
    ngram_range=(1, 2),
    random_state: int = 42,
    multi_class: bool = False
):
    """Обучает Logistic Regression (binary или 3-class) и логирует метрики."""
    df = pd.read_csv(data_path)

    # удаляем NaN и пустые тексты
    df = df.dropna(subset=["clean_text"])
    df = df[df["clean_text"].str.strip() != ""]

    X = df["clean_text"].astype(str)
    y = df[target_col]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=random_state, stratify=y
    )

    vectorizer = TfidfVectorizer(max_features=max_features, ngram_range=ngram_range)
    X_train_tfidf = vectorizer.fit_transform(X_train)
    X_test_tfidf = vectorizer.transform(X_test)

    if multi_class:
        model = LogisticRegression(
            max_iter=1000, multi_class="multinomial", random_state=random_state
        )
    else:
        model = LogisticRegression(max_iter=1000, random_state=random_state)

    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)

    # метрики
    acc = accuracy_score(y_test, y_pred)
    macro_f1 = f1_score(y_test, y_pred, average="macro")

    # отчёт в текстовый файл
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    with open(log_path, "w", encoding="utf-8") as f:
        f.write("=== Classification report ===\n")
        f.write(classification_report(y_test, y_pred))
        f.write(f"\nAccuracy: {acc:.4f}\nMacro-F1: {macro_f1:.4f}\n")

    # сохраняем артефакты
    os.makedirs(os.path.dirname(model_out), exist_ok=True)
    joblib.dump(model, model_out)
    joblib.dump(vectorizer, vectorizer_out)

    # логируем в MLflow
    with mlflow.start_run():
        mlflow.log_param("max_features", max_features)
        mlflow.log_param("ngram_range", ngram_range)
        mlflow.log_param("multi_class", multi_class)
        mlflow.log_metric("accuracy", acc)
        mlflow.log_metric("macro_f1", macro_f1)
        mlflow.sklearn.log_model(model, artifact_path="model")

    print(f"[OK] {target_col} | acc={acc:.4f} | f1={macro_f1:.4f}")


if __name__ == "__main__":
    # --- бинарная модель ---
    train_model(
        data_path="data/processed/reviews_binary_clean.csv",
        target_col="sentiment",
        model_out="models/model_lr_binary.pkl",
        vectorizer_out="models/tfidf_vectorizer_binary.pkl",
        log_path="logs/report_binary.txt",
        multi_class=False,
    )

    # --- трёхклассная модель ---
    train_model(
        data_path="data/processed/reviews_3class_clean.csv",
        target_col="sentiment_3class",
        model_out="models/model_lr_3class.pkl",
        vectorizer_out="models/tfidf_vectorizer_3class.pkl",
        log_path="logs/report_3class.txt",
        multi_class=True,
    )